const D=window.MAP_DATA, app=document.getElementById('app');
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const groups={'01_core':'核心骨架','02_concepts':'概念机制','03_read':'章节共读','04_practice':'实践反思','00_moc':'学习总览'};
const find=t=>D.notes.find(n=>n.title.replace(/\s/g,'')===t.replace(/\s/g,''));
const noteLink=(n,label)=>n?`<a href="#note/${n.id}">${escape(label||n.title)}</a>`:`<span class="missing">${escape(label||'待建笔记')}</span>`;
const chapters=D.notes.filter(n=>n.group==='03_read');
let selected=find('AI Agent')?.id, graphObserver, filter='all';
const connected=id=>D.notes.filter(n=>D.edges.some(e=>(e.source===id&&e.target===n.id)||(e.target===id&&e.source===n.id)));
function graphShell(){return `<div class="map-panel"><div class="map-head"><span>笔记双链 · 点击节点探索相邻笔记</span><span>实线：已有引用　虚线节点：待建笔记</span></div><div class="map-layout"><svg class="network" aria-label="可交互的笔记关系图" role="group"></svg><div class="map-detail" aria-live="polite"></div></div></div>`;}
function topicHome(){
const titles=['Agent 基础','上下文工程','记忆与知识库','工具与行动'];
const questions=['建立行动与反馈的循环','为当前判断准备信息','保存经验，按需找回依据','把能力连接到可靠行动'];
app.innerHTML=`<section class="garden-hero"><a class="back" href="#">← 回到花园</a><div class="eyebrow">AI AGENT · 学习地图</div><h1>AI Agent 思维学习</h1><p>从一个概念出发，点击节点，看见笔记之间的联系。</p></section>
<section class="section" style="margin-top:0"><div class="section-head"><h2>概念关系图</h2><p>${D.notes.length} 篇笔记 · ${D.edges.length} 条引用</p></div>${graphShell()}</section>
<section class="section"><div class="section-head"><h2>沿着问题，继续阅读</h2><p>四章共读，一条逐步深入的路径</p></div><div class="pathway">${chapters.map((n,i)=>`<a class="chapter ${i===3?'current':''}" href="#note/${n.id}"><span class="number">0${i+1}</span><div class="status">共读完成</div><h3>${titles[i]}</h3><p>${questions[i]}</p></a>`).join('')}</div></section>
<section class="section bottom-grid"><div><div class="section-head"><h2>把理解带回生活</h2></div><ul class="simple-list">${D.notes.filter(n=>n.group==='04_practice').map(n=>`<li>${noteLink(n)}<small>实践与反思记录　↗</small></li>`).join('')}</ul><p class="notice">实践反思是当时的经历记录，后续应用效果需继续验证。</p></div><div><div class="section-head"><h2>知识还在生长</h2></div><p class="notice">沿着笔记中的双链，探索概念之间的关系。</p><div class="related">${D.unresolved.map(x=>`<span class="missing">${escape(x)}</span>`).join('　')}</div><p><a class="back" href="#library">浏览全部笔记 →</a></p></div></section>`;mountGraph();}
function mountGraph(){const svg=app.querySelector('.network');if(!svg)return;graphObserver?.disconnect();graphObserver=new ResizeObserver(drawGraph);graphObserver.observe(svg);drawGraph();}
function drawGraph(){const svg=app.querySelector('.network');if(!svg)return;const active=D.notes.find(n=>n.id===selected)||D.notes[0];const w=svg.getBoundingClientRect().width,h=svg.getBoundingClientRect().height;svg.setAttribute('viewBox',`0 0 ${w} ${h}`);
const all=connected(active.id);const max=w<400?6:10;const related=[...all].sort((a,b)=>Number(b.group==='01_core')-Number(a.group==='01_core')).slice(0,max);const cx=w/2,cy=h/2,rx=Math.max(65,w/2-85),ry=h/2-65;const nodes=[{...active,x:cx,y:cy,center:true},...related.map((n,i)=>({...n,x:cx+rx*Math.cos(-Math.PI/2+i*2*Math.PI/related.length),y:cy+ry*Math.sin(-Math.PI/2+i*2*Math.PI/related.length)}))];
svg.innerHTML=`<title>${escape(active.title)} 的关联笔记</title>${nodes.slice(1).map(n=>`<line x1="${cx}" y1="${cy}" x2="${n.x}" y2="${n.y}"/>`).join('')}${nodes.map(n=>{const title=n.title.replace(/^第0\d章[_ ]*/, '').replace(/（.*?）/,'');const short=title.length>12?title.slice(0,11)+'…':title;return `<a href="#map" data-node="${n.id}" class="${n.center?'core':''}" aria-label="查看 ${escape(n.title)} 的关联"><title>${escape(n.title)}</title><circle cx="${n.x}" cy="${n.y}" r="${n.center?43:22}"/><text x="${n.x}" y="${n.y+(n.center?5:42)}" text-anchor="middle">${escape(short)}</text></a>`;}).join('')}`;
svg.querySelectorAll('[data-node]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();selected=a.dataset.node;drawGraph();}));
app.querySelector('.map-detail').innerHTML=`<span class="tag">${groups[active.group]||'笔记'}</span><h3>${escape(active.title)}</h3><p>${escape(active.excerpt||'沿着笔记中的双链，查看这个概念与章节、实践的联系。')}</p><a class="button" href="#note/${active.id}">阅读笔记 ↗</a><p>相邻笔记 ${all.length} 篇${all.length>max?` · 图中显示 ${max} 篇`:''}</p><div class="related">${all.map(n=>noteLink(n)).join('')}</div>`;
}
function library(){app.innerHTML=`<div class="eyebrow">NOTE LIBRARY</div><h1>每一篇，都是一个入口。</h1><div class="library-toolbar"><input id="search" aria-label="搜索笔记标题" placeholder="搜索笔记标题…"><div class="filters">${[['all','全部'],...Object.entries(groups)].map(([id,label])=>`<button data-filter="${id}" class="${filter===id?'active':''}">${label}</button>`).join('')}</div></div><div class="note-grid" id="results"></div>`;
function results(){const q=app.querySelector('#search').value.toLowerCase();const ns=D.notes.filter(n=>(filter==='all'||n.group===filter)&&n.title.toLowerCase().includes(q));app.querySelector('#results').innerHTML=ns.map(n=>`<a class="note-card" href="#note/${n.id}"><span class="tag">${groups[n.group]||'计划'}</span><h3>${escape(n.title)}</h3><p>${escape(n.excerpt.slice(0,85))}</p></a>`).join('')||'<p class="empty">没有匹配的笔记。</p>';}
app.querySelector('#search').addEventListener('input',results);app.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;app.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));results();});results();}
function read(id){const n=D.notes.find(x=>x.id===id);if(!n){app.innerHTML='<h1>未找到这篇笔记</h1><a href="#library">返回笔记列表</a>';return;}app.innerHTML=`<a class="back" href="#library">← 全部笔记</a><div class="reading"><aside><h3>相关笔记</h3>${connected(id).map(x=>noteLink(x)).join('')}</aside><article><p class="tag">${groups[n.group]||'学习计划'}</p>${n.html}<hr><p class="notice">来源：${escape(n.path)} · 学习笔记</p></article></div>`;}
function home(){app.innerHTML=`<section class="garden-hero"><div class="eyebrow">JINGJING’S LEARNING GARDEN</div><div class="garden-heading"><h1>玩索而有得</h1></div><p class="garden-intro">顺着好奇，找到一片认知新天地。<br>在这片花园里，慢慢长成自己的理解。</p><div class="writing-intent"><h2>关于这个花园</h2><p>这里记录我在学的东西——AI Agent、学习方法、以及“如何思考”本身。</p><p>90% 写给自己：把模糊的东西理清楚，把散落的认知连成线。<br>10% 留给恰好路过、想查点资料的人。</p><p>这里没有成品，只有正在生长的过程。</p></div></section><section class="section garden-themes"><div class="section-head"><div><div class="eyebrow">GROWING TOPICS</div><h2>沿着兴趣，走进一片花园</h2></div><p>一个主题，一本持续生长的笔记</p></div><div class="theme-columns"><a class="theme-card" href="#theme/ai-agent"><div class="theme-art"><span class="topic-index">主题 01</span><div class="mini-network"><i class="mini-center">Agent</i><i class="mini-one">LLM</i><i class="mini-two">Context</i><i class="mini-three">Tool</i></div><span class="theme-state">持续学习中</span></div><div class="theme-body"><span class="tag">技术 × 思维 × 日常实践</span><h3>AI Agent 思维学习</h3><p>从智能体的工作方式出发，理解信息、判断与行动，也重新观察自己的决策。</p><div class="theme-meta"><span>4 章共读</span><span>${D.notes.length} 篇演示笔记</span><span>概念地图</span></div><div class="theme-enter">走进这个主题 <span>↗</span></div></div></a><div class="future-plot"><div class="seed-mark">＋</div><h3>为下一次好奇，留一块空地。</h3><p>新的主题，会在这里慢慢长出来。<br>不用急着把每一处都填满。</p><span>下一个主题 · 尚未开始</span></div></div></section>${entryCards()}<section class="garden-bottom"><span class="eyebrow">HOW TO WANDER</span><div><h3>不必从第一页开始。</h3><p>选一个主题，沿章节走，也可以从一个概念出发，跟着笔记之间的链接漫游。未完成的想法，同样是学习的一部分。</p></div><a href="#map">先看 AI Agent 地图 ↗</a></section>`;}
function entryCards(){return `<section class="section"><div class="section-head"><h2>认识我，也认识我的思考</h2><p>给第一次来到这里的朋友</p></div><div class="entry-grid"><a class="entry-card" href="#about"><span class="tag">01 · 关于晶晶</span><h3>我为什么写这些笔记</h3><p>把阅读变成自己的理解，再带回日常的判断和行动。</p><span class="entry-arrow">认识我 →</span></a><a class="entry-card" href="#paths"><span class="tag">02 · 精选小径</span><h3>从一个问题开始漫游</h3><p>不用读完全部笔记，沿着一条线索，看看概念怎样连接。</p><span class="entry-arrow">选一条小径 →</span></a><a class="entry-card" href="#now"><span class="tag">03 · 最近在想</span><h3>把未完成的问题留下</h3><p>这一阶段的学习、尝试，以及准备继续追问的地方。</p><span class="entry-arrow">看看近况 →</span></a></div></section>`;}
function about(){app.innerHTML=`<a class="back" href="#">← 回到花园</a><div class="personal-page"><span class="eyebrow">关于晶晶</span><h1>打开自己，打开世界，<br>不再模糊，不再抽象。</h1><p class="personal-lead">你好，我是晶晶。这里是我按主题记录学习、整理思考的地方。</p><p>我希望学习不只停留在复述一本书，而是能理解它在说什么、知道它的边界，并把不同概念连起来，与生活中的成长和决策对照。</p><blockquote>90% 写给自己，10% 整理分享。<br>这是我写笔记的意图：大部分心力用来帮助自己理解，也愿意把理清的部分整理出来，与你分享。</blockquote><h2>这里怎样慢慢生长</h2><div class="about-steps"><div><span>读与问</span><p>先说出自己的理解，再用原文、反例和问题检验。</p></div><div><span>连接</span><p>把章节、概念和实践放在一起，留下关系与依据。</p></div><div><span>带回生活</span><p>从真实经历反思，也把尚未验证的想法如实标明。</p></div></div><h2>你可以这样逛</h2><p>从一个主题或问题进入，不必按顺序读。这里既有阶段总结，也有还在形成的理解；读过、讨论过和实际验证过，会尽量分开记录。</p><a class="button" href="#paths">从精选小径开始 ↗</a></div>`;}
function paths(){const routes=[{title:'Agent 怎样从理解走向行动？',intro:'先认识骨架，再看信息与工具怎样参与判断。',names:['AI Agent','Context','Tool']},{title:'保存的信息，怎样成为判断依据？',intro:'从记忆到检索，最后回到当前真正可见的上下文。',names:['Memory','Knowledge Base 知识库','Retrieval  RAG 检索增强生成','Context']},{title:'有能力之后，怎样把事情做可靠？',intro:'从接口与权限出发，理解等待、反馈和完成状态。',names:['工具设计','授权与安全','Task State','异步机制与事件驱动']}];app.innerHTML=`<a class="back" href="#">← 回到花园</a><div class="eyebrow page-eyebrow">精选小径</div><h1>带着一个问题，<br>沿着几篇笔记走走。</h1><p class="notice">按问题整理的阅读路线；路线顺序用于导览，具体概念关系以笔记内容为准。</p><div class="trail-list">${routes.map((r,i)=>`<section class="trail"><span class="number">0${i+1}</span><div><h2>${r.title}</h2><p>${r.intro}</p><ol class="trail-stops">${r.names.map(t=>`<li>${noteLink(find(t),t)}</li>`).join('')}</ol></div></section>`).join('')}</div><a class="back" href="#map">也可以从概念地图自由探索 →</a>`;}
function now(){app.innerHTML=`<a class="back" href="#">← 回到花园</a><div class="personal-page"><span class="eyebrow">最近在想</span><h1>理解在发生，<br>问题也在继续。</h1><p class="notice">本次整理：2026 年 9 月 8 日 · 阶段记录，不是自动更新的实时状态</p><section class="now-item"><span class="tag">正在学习</span><h2>AI Agent：从概念到行动闭环</h2><p>已共读前四章。第四章的讨论、测试与真实经历反思已完成，原书编程实验尚未运行。下一站是第五章。</p><a class="back" href="#theme/ai-agent">进入学习主题 →</a></section><section class="now-item"><span class="tag">正在尝试</span><h2>把笔记变成可以漫游的花园</h2><p>已经有了本地页面预览：主题入口、章节路线和笔记地图。接下来希望让每个主题对应一个 Obsidian 仓库，写作后可以更新网站。自动上传和公开发布尚未开启。</p></section><section class="now-item"><span class="tag">继续追问</span><h2>怎样才算真正完成一件事？</h2><p>工具返回成功、任务的一步完成、整个目标达成，并不是同一件事。我想继续把这个区别带到真实安排与协作中检验。</p>${noteLink(find('Task State'),'阅读：任务状态 →')}</section></div>`;}
function route(){graphObserver?.disconnect();const hash=location.hash.slice(1);if(hash==='about')about();else if(hash==='paths')paths();else if(hash==='now')now();else if(hash.startsWith('note/'))read(hash.slice(5));else if(hash.startsWith('theme/'))configuredTheme(hash.slice(6));else if(hash==='library')library();else if(hash==='map'){app.innerHTML=`<div class="eyebrow">CONNECTED IDEAS</div><h1>从一个概念，走向另一个。</h1><p class="notice">连线来自演示示例，展示概念地图的使用方式。</p>${graphShell()}`;mountGraph();}else home();window.scrollTo(0,0);}
const originalHome=home;
home=function(){originalHome();app.querySelector('.theme-columns').innerHTML=D.themes.map(t=>`<a class="theme-card" href="#theme/${t.id}">${t.id==='ai-agent'?'<div class="theme-art" aria-label="AI Agent 由 LLM、Context、Tool 构成"><div class="mini-network"><i class="mini-center">Agent</i><i class="mini-one">LLM</i><i class="mini-two">Context</i><i class="mini-three">Tool</i></div></div>':''}<div class="theme-body"><span class="tag">持续生长的学习主题</span><h3>${escape(t.title)}</h3><p>${escape(t.description)}</p><div class="theme-meta">${D.notes.filter(n=>n.theme===t.id).length} 篇公开笔记</div><div class="theme-enter">走进这个主题 ↗</div></div></a>`).join('');};
function configuredTheme(id){if(id==='ai-agent'){topicHome();return;}const t=D.themes.find(t=>t.id===id);if(!t){app.innerHTML='<h1>主题不存在</h1>';return;}const ns=D.notes.filter(n=>n.theme===id);app.innerHTML=`<a href="#" class="back">← 回到花园</a><h1>${escape(t.title)}</h1><p>${escape(t.description)}</p><div class="note-grid">${ns.map(n=>`<a class="note-card" href="#note/${n.id}"><h3>${escape(n.title)}</h3><p>${escape(n.excerpt)}</p></a>`).join('')}</div><h2>笔记之间的连接</h2><div class="related">${D.edges.filter(e=>ns.some(n=>n.id===e.source)&&ns.some(n=>n.id===e.target)).map(e=>noteLink(ns.find(n=>n.id===e.source))+' → '+noteLink(ns.find(n=>n.id===e.target))).join('<br>')||'还没有公开的双链，先从一篇笔记开始。'}</div>`;}
window.addEventListener('hashchange',route);route();
